#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_47
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_SPI_MOSI_PIN  GPIO_NUM_6
#define DISPLAY_SPI_SCLK_PIN  GPIO_NUM_7
#define DISPLAY_SPI_CS_PIN    GPIO_NUM_5
#define DISPLAY_SPI_DC_PIN    GPIO_NUM_4
#define DISPLAY_SPI_RESET_PIN GPIO_NUM_48

#endif
